version: "3.7"

networks:
  network:

volumes:
  pgdata:

services:
# Kong: The API Gateway
  kong:
    image: kong:3.1
    container_name: kong
    restart: always
    networks:
      - network
    env_file:
      - kong.env.example
    ports:
      - 48000:8000 # 接收处理 http 流量
      - 48443:8443 # 接收处理 https 流量
      #- 8001:8001 # http 管理 API
      #- 8444:8444 # https 管理 API
    depends_on:
      - postgresql

# Konga: Kong GUI
  konga:
    image: pantsel/konga:0.14.9
    container_name: konga
    restart: always
    networks:
      - network
    env_file:
      - kong.env.example
    ports:
      - 41337:1337
    depends_on:
      - postgresql

# PostgeSQL Datebase
  postgresql:
    image: postgres:11.1-alpine
    container_name: postgresql
    restart: always
    networks:
      - network
    ports:
      - 54324:5432
    env_file:
      - kong.env.example
    volumes:
      - pgdata:/var/lib/postgresql/data
